"""empty message

Revision ID: f26b5fc0730d
Revises: 9c13799525b1
Create Date: 2022-05-26 00:09:02.124440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f26b5fc0730d'
down_revision = '9c13799525b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('animals', 'extinto')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('animals', sa.Column('extinto', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###
